[package]
name = "saber_march"
version = "0.1.0"
authors = ["BuildTools <unconfigured@null.spigotmc.org>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.31.0", features = ["bundled", "static-link"] }